"""
Unit test suite for GW170817 Observational Strain Data Integration.

Verifies:
1. Local preprocessed observational asset (.npz) exists.
2. Time axis spans the intended [-10, +10] s window.
3. Time axis is strictly monotonic.
4. Time axis is centered around merger peak at t = 0 s (GPS 1187008882.43 s).
5. H1 detector strain data are present and non-empty.
6. L1 detector strain data are present and non-empty.
7. Sample rate matches 4096 Hz.
8. No NaNs or Infinite values exist in strain or time arrays.
9. Metadata fields (event_gps, sample_rate, detectors, conditioning_band) are populated.
10. Observed strain is structurally and scientifically distinct from model strain.
11. Physical model waveform remains driven by GravitationalWaveModel.
12. Observational time mapping uses the presentation clock without modifying physical event_time.
"""
import os
import unittest
import numpy as np

from gw170817.config import SimConfig
from gw170817.simulation.engine import GW170817Simulation
from gw170817.simulation.observational_data import ObservationalGWData
from gw170817.visualization.dashboard import ScientificDashboard


class TestObservationalGWStrain(unittest.TestCase):
    """Test suite for Observational GW170817 Strain Integration."""

    @classmethod
    def setUpClass(cls):
        cls.obs_data = ObservationalGWData()

    def test_observational_asset_existence(self):
        """Test local processed asset (.npz) exists and is loaded cleanly offline."""
        self.assertTrue(os.path.exists(self.obs_data.data_path), f"Asset file missing: {self.obs_data.data_path}")
        self.assertTrue(self.obs_data.loaded, "ObservationalGWData must load cleanly offline")

    def test_time_axis_bounds_and_monotonicity(self):
        """Test time axis spans [-10, +10] s and is strictly monotonic."""
        t_arr = self.obs_data.relative_time
        self.assertGreater(len(t_arr), 1000)

        self.assertAlmostEqual(t_arr[0], -10.0, delta=0.1)
        self.assertAlmostEqual(t_arr[-1], +10.0, delta=0.1)

        diffs = np.diff(t_arr)
        self.assertTrue(np.all(diffs > 0.0), "Time axis must be strictly monotonic")

    def test_merger_reference_centering(self):
        """Test event reference time t = 0 s aligns with merger peak."""
        t_arr = self.obs_data.relative_time
        idx_zero = np.argmin(np.abs(t_arr))
        self.assertAlmostEqual(t_arr[idx_zero], 0.0, delta=0.01)
        self.assertEqual(self.obs_data.event_gps, 1187008882.43)

    def test_h1_and_l1_data_presence(self):
        """Test both H1 and L1 detector strain series are populated."""
        h1 = self.obs_data.h1_strain
        l1 = self.obs_data.l1_strain

        self.assertEqual(len(h1), len(self.obs_data.relative_time))
        self.assertEqual(len(l1), len(self.obs_data.relative_time))

        self.assertGreater(np.max(np.abs(h1)), 0.0, "H1 strain must be non-zero")
        self.assertGreater(np.max(np.abs(l1)), 0.0, "L1 strain must be non-zero")

    def test_sample_rate_and_finiteness(self):
        """Test sample rate is 4096 Hz and arrays contain finite numeric values (no NaN/Inf)."""
        self.assertEqual(self.obs_data.sample_rate, 4096)

        self.assertTrue(np.all(np.isfinite(self.obs_data.relative_time)))
        self.assertTrue(np.all(np.isfinite(self.obs_data.h1_strain)))
        self.assertTrue(np.all(np.isfinite(self.obs_data.l1_strain)))

    def test_metadata_fields(self):
        """Test metadata fields are correctly populated."""
        self.assertIn("H1", self.obs_data.detectors)
        self.assertIn("L1", self.obs_data.detectors)
        self.assertIn("20-2000", self.obs_data.conditioning_band)
        self.assertIsNotNone(self.obs_data.processing_notes)

    def test_observed_vs_model_separation(self):
        """Test observed strain data and physical model waveform are structurally distinct products."""
        config = SimConfig(mode="DEV", seed=42)
        sim = GW170817Simulation(config=config)

        # Retrieve model waveform sample
        h_plus_model, h_cross_model = sim.gw_model.strain(sim.dynamics.inspiral_state)

        # Retrieve observed sample at current event_time
        h1_obs, l1_obs = self.obs_data.get_sample_at_time(sim.current_state.event_time)

        # Verify both exist as numbers and are generated by distinct code paths
        self.assertTrue(np.isfinite(h_plus_model))
        self.assertTrue(np.isfinite(h1_obs))
        self.assertTrue(np.isfinite(l1_obs))

    def test_sliding_window_decimation(self):
        """Test get_window returns a valid decimated sub-array for GPU rendering."""
        sub_t, sub_h1, sub_l1 = self.obs_data.get_window(t_center=-2.0, window_sec=1.5, n_samples=128)

        self.assertEqual(len(sub_t), 128)
        self.assertEqual(len(sub_h1), 128)
        self.assertEqual(len(sub_l1), 128)
        self.assertAlmostEqual(sub_t[0], -2.75, delta=0.05)
        self.assertAlmostEqual(sub_t[-1], -1.25, delta=0.05)


if __name__ == "__main__":
    unittest.main()
